{% set version = "1.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-scales
  version: {{ version|replace("-", "_") }}

source:
  fn: scales_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/scales_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/scales/scales_{{ version }}.tar.gz
  sha256: b33e0f6b44259551ce02befd52eac53602509fbfdd903920620c658c50f35888

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-farver >=2.0.0
    - r-r6
    - r-rcolorbrewer
    - r-lifecycle
    - r-labeling
    - r-munsell >=0.5
    - r-viridislite
  run:
    - r-base
    - r-farver >=2.0.0
    - r-r6
    - r-rcolorbrewer
    - r-lifecycle
    - r-labeling
    - r-munsell >=0.5
    - r-viridislite

test:
  commands:
    - $R -e "library('scales')"           # [not win]
    - "\"%R%\" -e \"library('scales')\""  # [win]

about:
  home: https://scales.r-lib.org, https://github.com/r-lib/scales
  license: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
  summary: Graphical scales map data to aesthetics, and provide methods for automatically determining breaks and labels for axes and legends.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
