appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: A7Q2QRvs5TfPcnSyV7A4HIBoEwM0PGVShBwGSVqn/qgb7aD9ZA1H3ZvtNG3NP4hr2IYexD/NgFeg6i9wkJfPCLfUKV5Twi7Gtq9f5OiAFXoozYeROY0QFlca+M2hhG725qxbOiG0KIbjeAB3sSI0zARTlLYJBFfsLt0ET8x3b8ShBFrgPSAGseUyAkDFej01yo7khD/86FH91WWLnnPP+2ZQcG3K6nboqVPozxWQ2wg3/ejdcsj+U+/sCv8yuKJYy2szvxqLHxf9H8YO/Lr1teBWrMhVaLmpe36indi5rWBMtL2+ilV4l7/Hz84bxcIbpPKzo9vEetRf7a+8Lj0tWOIajPXcz9WYga+zOIlYSYWWMexuzmlq/kQXLfNBSVlU9Gmw2WCi4tcgRJvz172DMpMJkdhYe+HtK9BoaF8I8lmqvaXQkmyfyTZMIErKas3/mjFncmgAQt3wGn0u3+vGKzPdYUzlQaMc2n3+ms8b2L9tbJcgG4EeL0AtSCHUn1TJqHshRArRFuDTC9Ogl82TqrdyL51Yv/eIvKp4I2W6wqa+A5C6kGfjk+tuDus9bG6342Eo/l8xwd1v4ut+wt+O4+NuLHOyvREYjZEl567RcP6nx9DrbB5gt0IwwzG0VMVN0KW2A4o8EanpWt8I31bPxkfNBVhZqI9ZD2Td0j91uUQ=
conda_forge_output_validation: true
